# Configurasi agar bisa baca file .env
spring.config.import=file:backend/demo/.env[.properties]

# buat koneksi dengan database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Configurasi biar bisa buat / update table secara otomatis
spring.jpa.hibernate.ddl-auto=update

# buat liat query yang dijalankan di console
spring.jpa.show-sql=true

spring.application.name=demo